---
deployment:
 tasks:
 - export DEPLOYPATH=/home/user/public_html/
  - export PROJECTROOT=/home/igmengct/peru_portfolio/
  - /bin/cp index.html $DEPLOYPATH
  - /bin/cp -R assets $DEPLOYPATH
  - /bin/cp $PROJECTROOT/* $DEPLOYPATH
